### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by leonroy** [deanlyoung/homebridge-airvisual-pro#1]
Seeing the following error on a new install:

```
Nov 04 13:36:48 homebridge homebridge[11892]: [11/4/2018, 1:36:48 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] AQI - 0 -> 4
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] PM2.5 (ug/m3) - 0 -> 1.0
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] PM10 (ug/m3) - undefined -> 2
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] Temperature (C) - 0 -> 21.5
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] Humidity (%) - 0 -> 49
Nov 04 13:36:58 homebridge homebridge[11892]: [11/4/2018, 1:36:58 PM] [AirVisual Pro] CO2 (ppm) - 0 -> 720
Nov 04 13:37:08 homebridge homebridge[11892]: [11/4/2018, 1:37:08 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:37:08 homebridge homebridge[11892]: [11/4/2018, 1:37:08 PM] [AirVisual Pro] AQI - 1 -> 4
Nov 04 13:37:18 homebridge homebridge[11892]: [11/4/2018, 1:37:18 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:37:18 homebridge homebridge[11892]: [11/4/2018, 1:37:18 PM] [AirVisual Pro] AQI - 1 -> 4
Nov 04 13:37:28 homebridge homebridge[11892]: [11/4/2018, 1:37:28 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:37:28 homebridge homebridge[11892]: [11/4/2018, 1:37:28 PM] [AirVisual Pro] AQI - 1 -> 4
Nov 04 13:37:38 homebridge homebridge[11892]: [11/4/2018, 1:37:38 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:37:38 homebridge homebridge[11892]: [11/4/2018, 1:37:38 PM] [AirVisual Pro] AQI - 1 -> 4
Nov 04 13:37:48 homebridge homebridge[11892]: [11/4/2018, 1:37:48 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:37:48 homebridge homebridge[11892]: [11/4/2018, 1:37:48 PM] [AirVisual Pro] AQI - 1 -> 4
Nov 04 13:37:58 homebridge homebridge[11892]: [11/4/2018, 1:37:58 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:37:58 homebridge homebridge[11892]: [11/4/2018, 1:37:58 PM] [AirVisual Pro] AQI - 1 -> 8
Nov 04 13:37:58 homebridge homebridge[11892]: [11/4/2018, 1:37:58 PM] [AirVisual Pro] PM2.5 (ug/m3) - 1 -> 2.0
Nov 04 13:38:08 homebridge homebridge[11892]: [11/4/2018, 1:38:08 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:38:08 homebridge homebridge[11892]: [11/4/2018, 1:38:08 PM] [AirVisual Pro] AQI - 1 -> 8
Nov 04 13:38:18 homebridge homebridge[11892]: [11/4/2018, 1:38:18 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:38:18 homebridge homebridge[11892]: [11/4/2018, 1:38:18 PM] [AirVisual Pro] AQI - 1 -> 8
Nov 04 13:38:28 homebridge homebridge[11892]: [11/4/2018, 1:38:28 PM] [AirVisual Pro] Refreshing values...
Nov 04 13:38:29 homebridge homebridge[11892]: [11/4/2018, 1:38:29 PM] [AirVisual Pro] AQI - 1 -> 8
Nov 04 13:38:34 homebridge homebridge[11892]: undefined:1
Nov 04 13:38:34 homebridge homebridge[11892]: SyntaxError: Unexpected end of JSON input
Nov 04 13:38:34 homebridge homebridge[11892]:     at JSON.parse (<anonymous>)
Nov 04 13:38:34 homebridge homebridge[11892]:     at exec (/usr/local/lib/node_modules/homebridge-airvisual-pro/index.js:63:27)
Nov 04 13:38:34 homebridge homebridge[11892]:     at ChildProcess.exithandler (child_process.js:282:5)
Nov 04 13:38:34 homebridge homebridge[11892]:     at emitTwo (events.js:126:13)
Nov 04 13:38:34 homebridge homebridge[11892]:     at ChildProcess.emit (events.js:214:7)
Nov 04 13:38:34 homebridge homebridge[11892]:     at maybeClose (internal/child_process.js:925:16)
Nov 04 13:38:34 homebridge homebridge[11892]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Nov 04 13:38:34 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 04 13:38:34 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.
Nov 04 13:38:44 homebridge systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Nov 04 13:38:44 homebridge systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 2.
Nov 04 13:38:44 homebridge systemd[1]: Stopped Node.js HomeKit Server.
```

**Comment by deanlyoung** [comment]
Thanks @leonroy! I’ll look into it. This may be why I’ve been having issues with products becoming disconnected, but I didn’t catch this in the logs.

**Comment by leonroy** [comment]
Alas no, still having an issue:
```
Nov 13 15:58:24 homebridge homebridge[74429]: [11/13/2018, 3:58:24 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:58:34 homebridge homebridge[74429]: [11/13/2018, 3:58:34 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:58:44 homebridge homebridge[74429]: [11/13/2018, 3:58:44 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:58:54 homebridge homebridge[74429]: [11/13/2018, 3:58:54 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:04 homebridge homebridge[74429]: [11/13/2018, 3:59:04 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:14 homebridge homebridge[74429]: [11/13/2018, 3:59:14 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:24 homebridge homebridge[74429]: [11/13/2018, 3:59:24 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:34 homebridge homebridge[74429]: [11/13/2018, 3:59:34 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:44 homebridge homebridge[74429]: [11/13/2018, 3:59:44 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:54 homebridge homebridge[74429]: [11/13/2018, 3:59:54 PM] [AirVisual Pro] Refreshing values...
Nov 13 15:59:54 homebridge homebridge[74429]: [11/13/2018, 3:59:54 PM] [AirVisual Pro] AQI - 4 -> 0
Nov 13 15:59:54 homebridge homebridge[74429]: [11/13/2018, 3:59:54 PM] [AirVisual Pro] PM2.5 (ug/m3) - 1 -> 0
Nov 13 15:59:54 homebridge homebridge[74429]: [11/13/2018, 3:59:54 PM] [AirVisual Pro] PM10 (ug/m3) - 1 -> 0
Nov 13 15:59:54 homebridge homebridge[74429]: [11/13/2018, 3:59:54 PM] [AirVisual Pro] CO2 (ppm) - 516 -> 517
Nov 13 16:00:04 homebridge homebridge[74429]: [11/13/2018, 4:00:04 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:00:14 homebridge homebridge[74429]: [11/13/2018, 4:00:14 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:00:24 homebridge homebridge[74429]: [11/13/2018, 4:00:24 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:00:34 homebridge homebridge[74429]: [11/13/2018, 4:00:34 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:00:44 homebridge homebridge[74429]: [11/13/2018, 4:00:44 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:00:54 homebridge homebridge[74429]: [11/13/2018, 4:00:54 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:01:04 homebridge homebridge[74429]: [11/13/2018, 4:01:04 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:01:14 homebridge homebridge[74429]: [11/13/2018, 4:01:14 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:01:24 homebridge homebridge[74429]: [11/13/2018, 4:01:24 PM] [AirVisual Pro] Refreshing values...
Nov 13 16:01:29 homebridge homebridge[74429]: undefined:1
Nov 13 16:01:29 homebridge homebridge[74429]: SyntaxError: Unexpected end of JSON input
Nov 13 16:01:29 homebridge homebridge[74429]:     at JSON.parse (<anonymous>)
Nov 13 16:01:29 homebridge homebridge[74429]:     at exec (/usr/local/lib/node_modules/homebridge-airvisual-pro/index.js:64:27)
Nov 13 16:01:29 homebridge homebridge[74429]:     at ChildProcess.exithandler (child_process.js:282:5)
Nov 13 16:01:29 homebridge homebridge[74429]:     at emitTwo (events.js:126:13)
Nov 13 16:01:29 homebridge homebridge[74429]:     at ChildProcess.emit (events.js:214:7)
Nov 13 16:01:29 homebridge homebridge[74429]:     at maybeClose (internal/child_process.js:925:16)
Nov 13 16:01:29 homebridge homebridge[74429]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Nov 13 16:01:29 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Nov 13 16:01:29 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.
Nov 13 16:01:40 homebridge systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
Nov 13 16:01:40 homebridge systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 3.
Nov 13 16:01:40 homebridge systemd[1]: Stopped Node.js HomeKit Server.
Nov 13 16:01:40 homebridge systemd[1]: Started Node.js HomeKit Server.
```

**Comment by deanlyoung** [comment]
Ahh, okay. I need to do some better error handling. Seems like there is some missing, malformed, or (as it says) undefined data being returned from your Node. Any chance you could share the data around that time?

**Comment by leonroy** [comment]
@deanlyoung the error appears to be occuring on this line in `index.js`:
```
exec('smbget -q -O -U ' + that.user + '%' + that.pass + ' smb://' + that.ip + '/airvisual/latest_config_measurements.json', (error, stdout, stderr) => {
      that.airdata = JSON.parse(stdout);
    });
```

Looking at `latest_config_measurements.json` it appears the file is a snapshot in time so it must get deleted/written periodically. Since the issue is intermittent could it be that `index.js` is falling over when the file is deleted/updated?

Happy to share the contents of the file but I think the script falls over when the file 'disappears' and AirVisual updates it with the latest data.

What do you reckon?

**Comment by deanlyoung** [comment]
Yeah, that sounds about right 😉

I am working on a fix that should handle errors around parsing “empty” (i.e. missing) data.

**Comment by deanlyoung** [comment]
Okay, give v1.0.6 a try!

**Comment by leonroy** [comment]
done, will let you know.

**Comment by leonroy** [comment]
no longer crashing, but HomeKit doesn't show any data from the AirVisual sensor now.

**Comment by leonroy** [comment]
just this over and over:
```
Nov 14 12:53:23 homebridge homebridge[848]: [11/14/2018, 12:53:23 PM] [AirVisual Pro] Refreshing values...
Nov 14 12:53:23 homebridge homebridge[848]: [11/14/2018, 12:53:23 PM] [AirVisual Pro] [stdout]: "{\n    \"date_and_time\": {\n        \"date\": \"2018/11/14\",\n
Nov 14 12:53:23 homebridge homebridge[848]: [11/14/2018, 12:53:23 PM] [AirVisual Pro] [error]: null
Nov 14 12:53:23 homebridge homebridge[848]: [11/14/2018, 12:53:23 PM] [AirVisual Pro] [stderr]: ""
```

**Comment by deanlyoung** [comment]
Looks like it’s either not parsing correctly (in which case I need to compare your file to mine). I can try from these outputs though.

Thanks!

**Comment by deanlyoung** [comment]
Thank you! Will take a look.

**Comment by hipuaa** [comment]
just this over and over error。

**Comment by deanlyoung** [comment]
@leonroy give me a shout here if it does (not) work

**Comment by leonroy** [comment]
thanks @deanlyoung appreciate the time spent on this - you can take out the debug messages now.

Reporting some further debug info. Seems the cause behind the original crashing is as below:

Normal output is:
```
Dec 12 14:29:26 homebridge homebridge[66614]: [12/12/2018, 2:29:26 PM] [AirVisual Pro] Refreshing values...
Dec 12 14:29:26 homebridge homebridge[66614]: [12/12/2018, 2:29:26 PM] [AirVisual Pro] [stdout]: "{\n    \"date_and_time\": {\n        \"date\": \"2018/12/12\",\n        \"time\": \"14:25:01\",\n        \"timestamp\": \"1544624701\"\n    },\n    \"measurements\": {\n        \"co2_ppm\": \"574\",\n        \"humidity_RH\": \"50\",\n        \"pm10_ugm3\": \"1\",\n        \"pm25_AQICN\": \"1\",\n        \"pm25_AQIUS\": \"4\",\n        \"pm25_ugm3\": \"1.0\",\n        \"temperature_C\": \"20.6\",\n        \"temperature_F\": \"69.1\",\n        \"voc_ppb\": \"-1\"\n    },\n    \"serial_number\": \"XXXX\",\n    \"settings\": {\n        \"follow_mode\": \"station\",\n        \"followed_station\": \"7526\",\n        \"is_aqi_usa\": true,\n        \"is_concentration_showed\": false,\n        \"is_indoor\": true,\n        \"is_lcd_on\": true,\n        \"is_network_time\": true,\n        \"is_temperature_celsius\": true,\n        \"language\": \"en-GB\",\n        \"lcd_brightness\": 0,\n        \"node_name\": \"Living room\",\n        \"power_saving\": {\n            \"2slots\": [\n                {\n                    \"hour_off\": 9,\n                    \"hour_on\": 7\n                },\n                {\n                    \"hour_off\": 22,\n                    \"hour_on\": 18\n                }\n            ],\n            \"mode\": \"yes\",\n            \"running_time\": 99,\n            \"yes\": [\n                {\n                    \"hour\": 8,\n                    \"minute\": 0\n                },\n                {\n                    \"hour\": 21,\n                    \"minute\": 0\n                }\n            ]\n        },\n        \"sensor_mode\": {\n            \"custom_mode_interval\": 3,\n            \"mode\": 1\n        },\n        \"speed_unit\": \"mph\",\n        \"timezone\": \"Europe/London\"\n    },\n    \"status\": {\n        \"app_version\": \"1.1623\",\n        \"battery\": 100,\n        \"datetime\": 1544624701,\n        \"device_name\": \"AIRVISUAL-XXXX\",\n        \"ip_address\": \"10.1.0.106\",\n        \"mac_address\": \"xxx\",\n        \"model\": \"20\",\n        \"sensor_pm25_serial\": \"xxx\",\n        \"sync_time\": 250000,\n        \"system_version\": \"KBG60F80\",\n        \"used_memory\": 3,\n        \"wifi_strength\": 4\n    }\n}\n"
Dec 12 14:29:26 homebridge homebridge[66614]: [12/12/2018, 2:29:26 PM] [AirVisual Pro] [error]: null
Dec 12 14:29:26 homebridge homebridge[66614]: [12/12/2018, 2:29:26 PM] [AirVisual Pro] [stderr]: ""
```

Error output `smbc_open: Connection timed out`. It does not take down Homebridge though so nice work 👍:
```
Dec 12 14:29:36 homebridge homebridge[66614]: [12/12/2018, 2:29:36 PM] [AirVisual Pro] Refreshing values...
Dec 12 14:29:41 homebridge homebridge[66614]: [12/12/2018, 2:29:41 PM] [AirVisual Pro] [stdout]: ""
Dec 12 14:29:41 homebridge homebridge[66614]: [12/12/2018, 2:29:41 PM] [AirVisual Pro] [error]: {"killed":false,"code":1,"signal":null,"cmd":"smbget -q -O -U airvisual%XXXXX smb://10.1.0.106/airvisual/latest_config_measurements.json"}
Dec 12 14:29:41 homebridge homebridge[66614]: [12/12/2018, 2:29:41 PM] [AirVisual Pro] [stderr]: "smbc_open: Connection timed out\n"
```

**Comment by deanlyoung** [comment]
optional logging added
